channels:
  - conda-forge
  - defaults
dependencies:
  - geopandas
  - osmnx
  - networkx
  - black
  - configparser
  - contextily
  - flake8
  - graphviz
  - isort
  - mypy
  - pre-commit
  - pandas-profiling
  - pandera
  - pip
  - pyjanitor
  - pysal
  - pytest
  - pytest-cov
  - python=3.8
  - python-dotenv
  - sphinx >= 1.7
  - sphinx-automodapi
  - sphinxcontrib-napoleon
  - sphinx_rtd_theme
  # jupyter lab/notebook tools
  - ipykernel
  - ipywidgets
  - nb_black
  - watermark
